In [129]:
%reload_ext autoreload
%autoreload 2
import re
import urllib
from bs4 import BeautifulSoup
import pandas as pd
import datetime
from geocloak.datautilus.downloader import NRTDataDownloader

In [123]:
pd.date_range(datetime.date(2024,1,12), datetime.datetime.now())

DatetimeIndex(['2024-01-12', '2024-01-13', '2024-01-14', '2024-01-15',
               '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19',
               '2024-01-20', '2024-01-21',
               ...
               '2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08',
               '2024-07-09', '2024-07-10'],
              dtype='datetime64[ns]', length=181, freq='D')

In [130]:
a = NRTDataDownloader()
a.check_data_status()

('2015-01-01T00:00Z', '2024-07-08T23:59:59Z')

In [141]:
df1, df2 = a.get_DSCOVRdata(start_date='2024-07-05T23:59:59Z')

In [142]:
df1.shape, df2.shape

((5760, 11), (5760, 3))

In [126]:
a = requests.get("https://www.ngdc.noaa.gov/next-catalogs/rest/dscovr/catalog/filename?processEnvs=oe&dataTypes=f1m,mg1&dataStartTime=2023-12-29T00:00Z&dataEndTime=2024-12-30T23:59Z")

In [143]:
df1.join(df2)

,bt,bx_gse,bx_gsm,by_gse,by_gsm,bz_gse,bz_gsm,theta_gse,theta_gsm,phi_gse,phi_gsm,proton_speed,proton_density,proton_temperature
Time,,,,,,,,,,,,,,
2024-07-05 00:00:00,5.10,-2.96,-2.96,4.12,4.09,0.37,0.63,4.160000,7.150000,125.660004,125.870003,340.899994,23.590000,51743.0
2024-07-05 00:01:00,4.80,-2.22,-2.22,3.98,4.06,-1.36,-1.10,-16.570000,-13.350000,119.129997,118.660004,340.799988,23.360001,52318.0
2024-07-05 00:02:00,5.00,-2.53,-2.53,4.29,4.30,-0.31,-0.03,-3.530000,-0.380000,120.519997,120.459999,341.000000,23.820000,52379.0
2024-07-05 00:03:00,5.16,-2.61,-2.61,4.37,4.40,-0.63,-0.35,-7.080000,-3.950000,120.809998,120.629997,340.299988,23.360001,51233.0
2024-07-05 00:04:00,4.43,-1.56,-1.56,3.52,3.63,-1.79,-1.56,-24.889999,-21.559999,113.949997,113.320000,339.500000,23.889999,50603.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-08 23:55:00,4.52,3.66,3.66,-2.42,-2.38,-1.01,-1.10,-12.910000,-14.090000,326.500000,326.929993,375.700012,4.250000,67552.0
2024-07-08 23:56:00,4.45,3.90,3.90,-1.78,-1.74,-1.16,-1.23,-15.180000,-16.059999,335.399994,335.950012,375.700012,4.100000,76707.0
2024-07-08 23:57:00,4.48,3.52,3.52,-2.51,-2.46,-1.13,-1.23,-14.710000,-15.940000,324.529999,325.000000,374.899994,4.260000,66354.0
2024-07-08 23:58:00,4.48,3.53,3.53,-2.46,-2.41,-1.19,-1.28,-15.460000,-16.660000,325.179993,325.679993,375.500000,4.440000,65140.0
2024-07-08 23:59:00,4.47,3.67,3.67,-2.28,-2.23,-1.09,-1.17,-14.170000,-15.270000,328.230011,328.700012,374.799988,4.060000,68672.0

In [139]:
df1

,bt,bx_gse,bx_gsm,by_gse,by_gsm,bz_gse,bz_gsm,theta_gse,theta_gsm,phi_gse,phi_gsm,overall_quality
Time,,,,,,,,,,,,
2024-07-05 00:00:00,5.10,-2.96,-2.96,4.12,4.09,0.37,0.63,4.160000,7.150000,125.660004,125.870003,0.0
2024-07-05 00:01:00,4.80,-2.22,-2.22,3.98,4.06,-1.36,-1.10,-16.570000,-13.350000,119.129997,118.660004,0.0
2024-07-05 00:02:00,5.00,-2.53,-2.53,4.29,4.30,-0.31,-0.03,-3.530000,-0.380000,120.519997,120.459999,0.0
2024-07-05 00:03:00,5.16,-2.61,-2.61,4.37,4.40,-0.63,-0.35,-7.080000,-3.950000,120.809998,120.629997,0.0
2024-07-05 00:04:00,4.43,-1.56,-1.56,3.52,3.63,-1.79,-1.56,-24.889999,-21.559999,113.949997,113.320000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-08 23:55:00,4.52,3.66,3.66,-2.42,-2.38,-1.01,-1.10,-12.910000,-14.090000,326.500000,326.929993,0.0
2024-07-08 23:56:00,4.45,3.90,3.90,-1.78,-1.74,-1.16,-1.23,-15.180000,-16.059999,335.399994,335.950012,0.0
2024-07-08 23:57:00,4.48,3.52,3.52,-2.51,-2.46,-1.13,-1.23,-14.710000,-15.940000,324.529999,325.000000,0.0
2024-07-08 23:58:00,4.48,3.53,3.53,-2.46,-2.41,-1.19,-1.28,-15.460000,-16.660000,325.179993,325.679993,0.0
2024-07-08 23:59:00,4.47,3.67,3.67,-2.28,-2.23,-1.09,-1.17,-14.170000,-15.270000,328.230011,328.700012,0.0

In [140]:
df2

,proton_speed,proton_density,proton_temperature,overall_quality
Time,,,,
2024-07-05 00:00:00,340.899994,23.590000,51743.0,0.0
2024-07-05 00:01:00,340.799988,23.360001,52318.0,0.0
2024-07-05 00:02:00,341.000000,23.820000,52379.0,0.0
2024-07-05 00:03:00,340.299988,23.360001,51233.0,0.0
2024-07-05 00:04:00,339.500000,23.889999,50603.0,0.0
...,...,...,...,...
2024-07-08 23:55:00,375.700012,4.250000,67552.0,0.0
2024-07-08 23:56:00,375.700012,4.100000,76707.0,0.0
2024-07-08 23:57:00,374.899994,4.260000,66354.0,0.0
2024-07-08 23:58:00,375.500000,4.440000,65140.0,0.0
2024-07-08 23:59:00,374.799988,4.060000,68672.0,0.0